trigger:
- master

pool:
  name: Default
  

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
# - task: Maven@4
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'clean compile'

- script: mvn test -Dbrowser=localchrome
  displayName: 'Run Tests'

- script: mvn surefire-report:report-only
  displayName: 'Generate Test Report'

- script: mvn site -DgenerateReports=false
  displayName: 'Generate Site Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/site'
    artifactName: 'TestReport'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'
